# Generated by Django 4.2 on 2025-02-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=100)),
                ('cognom1', models.CharField(max_length=100)),
                ('cognom2', models.CharField(blank=True, max_length=100, null=True)),
                ('correu', models.EmailField(max_length=254, unique=True)),
                ('moduls', models.IntegerField()),
            ],
        ),
    ]
